### ISSUE TITLE
Plugin 1

### ISSUE THREAD

**Issue by Kenshayy** [Kenshayy/plugin#1]
package me.kenshay.test;

import org.bukkit.Bukkit;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.block.BlockBreakEvent;
import org.bukkit.event.block.BlockPlaceEvent;
import org.bukkit.plugin.java.JavaPlugin;

import net.md_5.bungee.api.ChatColor;

public class Main extends JavaPlugin
  implements Listener
{
    public void onEnable()
    {
    	getLogger().info("Plugin abilitato correttamente");
    	Bukkit.getServer().getPluginManager().registerEvents(this, this);
    }
   
    public void onDisable()
    {
    	
    }
    
    @EventHandler(priority = EventPriority.HIGHEST)
    public void onDestroy(BlockBreakEvent event)
    {
    	Player player = event.getPlayer();
    	
    	if(player.hasPermission("distruggi.distruggi"))
    	{
    		
    	}else{
    		event.setCancelled(true);
    		player.sendMessage(ChatColor.RED + "Non puoi distruggere qui.");
    	}
    }
    
    @EventHandler(priority = EventPriority.HIGHEST)
    public void onPlace(BlockPlaceEvent event)
    {
    	Player player = event.getPlayer();
    	
    	if(player.hasPermission("piazza.piazza"))
    	{
    		
    	}else{
    		event.setCancelled(true);
    		player.sendMessage(ChatColor.RED + "Non puoi piazzare qui.");
    	}
    }

**Comment by C0mm4nd** [comment]
Manca @Override

**Comment by C0mm4nd** [comment]
Nabbo
